### ISSUE TITLE
Refget checksum calculation (ga4gh ) not working 

### ISSUE THREAD

**Issue by waterflow80** [EBIvariation/eva-seqcol#4]
@tcezard 
I tried to implement the checksum calculation algorithm `ga4gh` like this:

```java
public class SHA512Calculator extends ChecksumCalculator{

    @Override
    /**
     * Calculate the refget checksum (ga4gh) of the given sequence
     * */
    public String calculateChecksum(String sequence) {
        String sequence1 = sequence.replaceAll("[\\W]|_", ""); // Remove non-alphanumeric characters
        String sequence2 =  SHA512Hash(sequence1.toUpperCase());
        byte[] sequenceBytes = sequence2.getBytes();

        // Encode the first 24 bytes with Base64
        byte[] truncatedSequence = Arrays.copyOfRange(sequenceBytes, 0, 24);
        String encodedBase64Sequence = Base64.getUrlEncoder().encodeToString(truncatedSequence);

        String finalSequence = "SQ." + encodedBase64Sequence;
        return finalSequence;
    }

    public String SHA512Hash(String text) {
        MessageDigest md;
        try {
            md = MessageDigest.getInstance("SHA-512");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        md.update(text.getBytes());
        byte[] digest = md.digest();
        String textHash = DatatypeConverter
                .printHexBinary(digest).toUpperCase();
        return textHash.toLowerCase();
    }
}
```
For some reason I'm getting the wrong digest.
Am I missing some steps ?
Or there are some specific java classes that should be used?

**Comment by tcezard** [comment]
Not sure without more testing. I've use [this code](https://github.com/ga4gh/vrs-python/blob/6a70bdea4e5514834fb5fbd4f99fe84926ff2dd8/src/ga4gh/core/_internal/digests.py#L12) as standard implementation but it's in python. 
I suggest you put your code in a PR with some test that shows the current behaviour. That would help us pull it and test on our side.

**Comment by waterflow80** [comment]
@tcezard
Sorry I forgot to link the corresponding PR. 
The implementation is in this [PR](https://github.com/EBIvariation/eva-seqcol/pull/3/commits/cbc4161ae05f1d3cd2608da16153a86b55429a35#diff-2a66fa29a4f78faef97ccdee4f1cd779972711f00f0c2a87ae7d97e7d771c35e).

**Comment by tcezard** [comment]
This is resolved
