### ISSUE TITLE
Confusing sequence (chromosome) identifiers in the FASTA files

### ISSUE THREAD

**Issue by waterflow80** [EBIvariation/eva-seqcol#5]
@tcezard 
I've been downloading multiple assemblies (both report and FASTA files) and I've noticed that some sequences' 
FASTA files identify their sequences with the **refseq** identifier, eg ( **GCF_000001765.3**):

- FASTA file: 
![sequence-refseq-identifier](https://github.com/EBIvariation/eva-seqcol/assets/82417779/f28e7021-45e6-4f7e-9e73-e0c70c4788f0)
- Assembly report file:
![report-refseq-id](https://github.com/EBIvariation/eva-seqcol/assets/82417779/45d6dc8b-5098-4917-bcf9-c8fde5b7de8c)

And some other files identify their sequences with **GenBank-Acc** (**insdc_accession** attribute in Java), eg: (**GCF_000146045.2**):
- FASTA file: 
![sequence-genban-identifier](https://github.com/EBIvariation/eva-seqcol/assets/82417779/4eedd55e-a1c4-426e-900b-e5d259c3a9cc)

- Assembly report file:
![report-genbank-identifier](https://github.com/EBIvariation/eva-seqcol/assets/82417779/f056c610-8cbd-46b5-885d-cbe0c54796e6)

This made it a little bit more complicate when trying to **map** a **sequence** with the correct assembly report **entry**.
So I want to know if there's a way to know what **naming convention** is used to identify the sequences in the FASTA file **before processing** it. Because that will save us a lot of time in the processing.
Or, is there a pattern that allows me to identify whether an accession is a **Genbank-acc** or **Refseq**, so I can at least verify it only for the first sequence parsed, and do the switch...case later.

**Comment by tcezard** [comment]
All assemblies starting in GCA comes from INSDC and will contain sequence named with INSDC (GenBank) accessions. 
All assemblies starting in GCF comes from RefSeq and will contain sequence named with RefSeq accessions. 

You can know which accession to lookup based on the prefix of the assembly accession.

**Comment by waterflow80** [comment]
Clear, thank you.
