### ISSUE TITLE
reverting back to 'sorted_name_length_pairs' (underscore instead of hyphen)

### ISSUE THREAD

**Issue by waterflow80** [EBIvariation/eva-seqcol#50]
> I would like to know whether we should use `sorted_names_length_pairs`, as provided in the service-info file, or `sorted_name_length_pairs` as we defined it in our java model.

It should be `sorted_name_length_pairs`

_Originally posted by @nsheff in https://github.com/EBIvariation/eva-seqcol/issues/43#issuecomment-1708421519_

**Comment by tcezard** [comment]
And the change from hyphen to underscore also applies to:
 - the `md5_sequences` attribute
 - the comparison function attributes `a_only`, `b_only`, `a_and_b` and `a_and_b_same_order`

**Comment by waterflow80** [comment]
@tcezard 
Sorry I haven't noticed that you've already changed the name of the issue
